imports:
- path: templates/networking/network-template.jinja
  name: network.jinja
- path: templates/networking/subnetwork-template.jinja
  name: subnetwork.jinja
- path: templates/compute/instance-group-template.jinja
  name: instance-group.jinja
- path: templates/networking/firewall-rule-template.jinja
  name: firewall-rule.jinja
- path: templates/storage/cloud-sql-template.jinja
  name: cloud-sql.jinja
- path: templates/storage/cloud-storage-template.jinja
  name: cloud-storage.jinja
- path: templates/networking/load-balancer-template.jinja
  name: load-balancer.jinja

resources:
# Network configuration for web servers
- name: compute-net
  type: network.jinja

# Subnetwork configuration (One for each region)
- name: london
  type: subnetwork.jinja
  properties:
    network: compute-net
    ipCidrRange: 10.0.0.0/24
    region: europe-west2

- name: frankfurt
  type: subnetwork.jinja
  properties:
    network: compute-net
    ipCidrRange: 10.1.0.0/24
    region: europe-west3

# Create firewall rules for restricted access to compute resources
# Allow HTTP connections from all source ranges to compute machines
- name: compute-allow-http
  type: firewall-rule.jinja
  properties:
    network: compute-net
    sourceRanges: [0.0.0.0/0]
    IPProtocol: TCP
    ports: ["80", "443"]

# Cloud SQL storage and database configuration
- name: london-15599328
  type: cloud-sql.jinja
  properties:
    database:
      db_name: users15599328

# Create a multi-region (eu) cloud storage bucket for IoT sensor device data
- name: sensor-data
  type: cloud-storage.jinja
  
# Create an external load balancer to balance incoming HTTP traffic
- name: london-lb
  type: load-balancer.jinja
  properties:
    port: 443
    region: europe-west2

- name: frankfurt-lb
  type: load-balancer.jinja
  properties:
    port: 443
    region: europe-west3

# 2 regional managed instance group to act as Web servers for user access
- name: london-instances
  type: instance-group.jinja
  properties:
    instanceTemplate: instance-template
    region: europe-west2
    network: compute-net
    subnetwork: subnet-london
    targetPools: [$(ref.london-lp-tp.selfLink)]

- name: frankfurt-instances
  type: instance-group.jinja
  properties:
    instanceTemplate: instance-template
    region: europe-west3
    network: compute-net
    subnetwork: subnet-frankfurt
    targetPools: [$(ref.frankfurt-lp-tp.selfLink)]

# Google Cloud Storage for IoT sensor data


# App Engine to host IoT API


# Create VPN Gateway and Tunnel


# Create Loadbalancer for public traffic